ALTER TABLE "people"
  ADD COLUMN IF NOT EXISTS "is_recruiter" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "linkedin_url" VARCHAR(500),
  ALTER COLUMN "email" DROP NOT NULL,
  ALTER COLUMN "phone" DROP NOT NULL,
  ALTER COLUMN "company" DROP NOT NULL;
